version: "3.9"

services:
  api:
    image: ${DOCKER_USERNAME}/webshop-api:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: webshop-backend-net
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ConnectionStrings__Default: ${DB_CONNECTION_STRING:-Server=db;Port=3306;Database=emo_db;User Id=tru123;Password=tru12345;SslMode=None;}
      Jwt__Issuer: ${JWT_ISSUER:-EmoApi}
      Jwt__Audience: ${JWT_AUDIENCE:-EmoClient}
      Jwt__Secret: ${JWT_SECRET:-CHANGE_ME_SUPER_SECRET_MIN_32_CHARS_1234567}
    ports:
      - "5193:8080"
    restart: always

  client:
    image: ${DOCKER_USERNAME}/webshop-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5193}
    container_name: webshop-client
    depends_on:
      api:
        condition: service_started
    ports:
      - "5173:80"
    restart: always
