name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  CLIENT_DIR: client
  SERVER_PROJECT: server/EmoApi.csproj
  API_IMAGE: ${{ format('{0}/webshop-api', secrets.DOCKER_USERNAME) }}
  CLIENT_IMAGE: ${{ format('{0}/webshop-client', secrets.DOCKER_USERNAME) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ${{ env.CLIENT_DIR }}/package-lock.json

      - name: Install client dependencies
        working-directory: ${{ env.CLIENT_DIR }}
        run: npm ci

      - name: Build client bundle
        working-directory: ${{ env.CLIENT_DIR }}
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore server dependencies
        run: dotnet restore ${{ env.SERVER_PROJECT }}

      - name: Build server
        run: dotnet build ${{ env.SERVER_PROJECT }} --configuration Release --no-restore

  publish:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.API_IMAGE }}:latest
            ${{ env.API_IMAGE }}:${{ github.sha }}

      - name: Build and push Client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL || 'http://localhost:5193' }}
          tags: |
            ${{ env.CLIENT_IMAGE }}:latest
            ${{ env.CLIENT_IMAGE }}:${{ github.sha }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Validate deploy secrets (safe for multiline, no expansion)
        shell: bash
        run: |
          set -euo pipefail
          # Dùng SINGLE QUOTES để KHÔNG expand ${VAR} bên trong secret
          SSH_HOST='${{ secrets.SSH_HOST }}'
          SSH_USER='${{ secrets.SSH_USER }}'
          SSH_PRIVATE_KEY='${{ secrets.SSH_PRIVATE_KEY }}'
          DOCKER_USERNAME='${{ secrets.DOCKER_USERNAME }}'
          DOCKER_PASSWORD='${{ secrets.DOCKER_PASSWORD }}'
          DOCKER_COMPOSE_FILE='${{ secrets.DOCKER_COMPOSE_FILE }}'

          echo "len(SSH_HOST)=$(printf %s "$SSH_HOST" | wc -c)"
          echo "len(SSH_USER)=$(printf %s "$SSH_USER" | wc -c)"
          echo "len(SSH_PRIVATE_KEY)=$(printf %s "$SSH_PRIVATE_KEY" | wc -c)"
          echo "len(DOCKER_USERNAME)=$(printf %s "$DOCKER_USERNAME" | wc -c)"
          echo "len(DOCKER_PASSWORD)=$(printf %s "$DOCKER_PASSWORD" | wc -c)"
          echo "len(DOCKER_COMPOSE_FILE)=$(printf %s "$DOCKER_COMPOSE_FILE" | wc -c)"

          [[ -z "$SSH_HOST" ]] && { echo "SSH_HOST empty"; exit 1; }
          [[ -z "$SSH_USER" ]] && { echo "SSH_USER empty"; exit 1; }
          [[ -z "$SSH_PRIVATE_KEY" ]] && { echo "SSH_PRIVATE_KEY empty"; exit 1; }
          [[ -z "$DOCKER_USERNAME" ]] && { echo "DOCKER_USERNAME empty"; exit 1; }
          [[ -z "$DOCKER_PASSWORD" ]] && { echo "DOCKER_PASSWORD empty"; exit 1; }
          [[ -z "$DOCKER_COMPOSE_FILE" ]] && { echo "DOCKER_COMPOSE_FILE empty"; exit 1; }

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 10m
          script: |
            set -euo pipefail

            # Fallback DEPLOY_PATH
            DEPLOY_DIR="${{ secrets.DEPLOY_PATH }}"
            if [ -z "${DEPLOY_DIR}" ]; then
              DEPLOY_DIR="$HOME/Webshop"
            fi

            mkdir -p "$DEPLOY_DIR"
            cd "$DEPLOY_DIR"

            # Ghi compose từ secret, dùng quoted heredoc để KHÔNG expand
            cat > docker-compose.yml <<'EOF'
            ${{ secrets.DOCKER_COMPOSE_FILE }}
            EOF
            echo "[INFO] docker-compose.yml written."

            # Chọn docker compose CLI
            if command -v docker-compose >/dev/null 2>&1; then DC="docker-compose"; else DC="docker compose"; fi

            # Validate
            $DC config >/dev/null

            # Login & pull
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            DOCKER_USERNAME="${DOCKER_USERNAME}" $DC pull

            # Up
            DOCKER_USERNAME="${DOCKER_USERNAME}" $DC up -d --remove-orphans

            docker image prune -f || true
            echo "[INFO] Deploy done."
